In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

In [31]:
# Loading data 
bids = pd.read_csv("bids.csv")
bids.head()

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,home goods,phone2,9759243157894736,py,112.54.208.157,vasstdc27m7nks3
3,3,3939ac3ef7d472a59a9c5f893dd3e39fh9ofi,jefix,jewelry,phone4,9759243157894736,in,18.99.175.133,vasstdc27m7nks3
4,4,8393c48eaf4b8fa96886edc7cf27b372dsibi,jefix,jewelry,phone5,9759243157894736,in,145.138.5.37,vasstdc27m7nks3

In [32]:
train = pd.read_csv("train.csv")
train.head()

,bidder_id,payment_account,address,outcome
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0
1,624f258b49e77713fc34034560f93fb3hu3jo,a3d2de7675556553a5f08e4c88d2c228v1sga,ae87054e5a97a8f840a3991d12611fdcrfbq3,0.0
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,a3d2de7675556553a5f08e4c88d2c2280cybl,92520288b50f03907041887884ba49c0cl0pd,0.0
3,4bee9aba2abda51bf43d639013d6efe12iycd,51d80e233f7b6a7dfdee484a3c120f3b2ita8,4cb9717c8ad7e88a9a284989dd79b98dbevyi,0.0
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,a3d2de7675556553a5f08e4c88d2c22857ddh,2a96c3ce94b3be921e0296097b88b56a7x1ji,0.0

In [33]:
len(bids.index)

7656334

In [34]:
len(train.index)

2013

In [35]:
# Merge on train df
dataset = pd.merge(train,bids, on = "bidder_id", how ="left")
dataset.to_csv("dataset.csv")

In [36]:
# Reload the dataset 
df = pd.read_csv("dataset.csv")
df.head()

,Unnamed: 0,bidder_id,payment_account,address,outcome,bid_id,auction,merchandise,device,time,country,ip,url
0,0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,85371.0,yitr4,home goods,phone35,9.759489e+15,ke,82.34.177.248,vasstdc27m7nks3
1,1,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,274487.0,btpyy,home goods,phone1004,9.760249e+15,zm,202.130.71.167,vasstdc27m7nks3
2,2,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,527436.0,kj2ko,home goods,phone4,9.762261e+15,ke,22.54.76.225,vasstdc27m7nks3
3,3,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,554135.0,1m5t8,home goods,phone4,9.762431e+15,ke,32.13.237.126,vasstdc27m7nks3
4,4,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,607628.0,btpyy,home goods,phone4,9.762789e+15,ke,202.236.188.240,vasstdc27m7nks3

In [37]:
len(df.index)

3071253

In [38]:
df.set_index("Unnamed: 0", inplace= True)

In [39]:
df.head()

,bidder_id,payment_account,address,outcome,bid_id,auction,merchandise,device,time,country,ip,url
Unnamed: 0,,,,,,,,,,,,
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,85371.0,yitr4,home goods,phone35,9.759489e+15,ke,82.34.177.248,vasstdc27m7nks3
1,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,274487.0,btpyy,home goods,phone1004,9.760249e+15,zm,202.130.71.167,vasstdc27m7nks3
2,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,527436.0,kj2ko,home goods,phone4,9.762261e+15,ke,22.54.76.225,vasstdc27m7nks3
3,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,554135.0,1m5t8,home goods,phone4,9.762431e+15,ke,32.13.237.126,vasstdc27m7nks3
4,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,607628.0,btpyy,home goods,phone4,9.762789e+15,ke,202.236.188.240,vasstdc27m7nks3

In [41]:
df.loc[df["outcome"] == 0.0]

,bidder_id,payment_account,address,outcome,bid_id,auction,merchandise,device,time,country,ip,url
Unnamed: 0,,,,,,,,,,,,
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,85371.0,yitr4,home goods,phone35,9.759489e+15,ke,82.34.177.248,vasstdc27m7nks3
1,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,274487.0,btpyy,home goods,phone1004,9.760249e+15,zm,202.130.71.167,vasstdc27m7nks3
2,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,527436.0,kj2ko,home goods,phone4,9.762261e+15,ke,22.54.76.225,vasstdc27m7nks3
3,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,554135.0,1m5t8,home goods,phone4,9.762431e+15,ke,32.13.237.126,vasstdc27m7nks3
4,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,607628.0,btpyy,home goods,phone4,9.762789e+15,ke,202.236.188.240,vasstdc27m7nks3
...,...,...,...,...,...,...,...,...,...,...,...,...
3071248,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,a3d2de7675556553a5f08e4c88d2c22856leq,d02c2b288b8aabd79ff47118aff41a2dqwzwc,0.0,609792.0,jefix,mobile,phone316,9.762802e+15,id,28.18.7.49,ar89au37swuzvzz
3071249,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,a3d2de7675556553a5f08e4c88d2c22856leq,d02c2b288b8aabd79ff47118aff41a2dqwzwc,0.0,2297899.0,jefix,mobile,phone33,9.772601e+15,id,161.237.171.157,ar89au37swuzvzz
3071250,0381a69b7a061e9ace2798fd48f1f537mgq57,fd87037ce0304077079c749f420f0b4c54uo0,f030a221726fbcdfc4dc7dfd1b381a112hieq,0.0,3400601.0,jqx39,office equipment,phone11,9.636754e+15,sa,54.212.21.87,cgb17jpn1ixq9hw
3071251,84a769adc98498f52debfe57b93a0789556f4,fbe0ce34d6546ebd9e4c63afc68b085byd2tf,a3d2de7675556553a5f08e4c88d2c228fib6p,0.0,2007255.0,ntjde,jewelry,phone59,9.770756e+15,ru,79.72.96.0,9ov8hm82p20sxlz
3071252,84a769adc98498f52debfe57b93a0789556f4,fbe0ce34d6546ebd9e4c63afc68b085byd2tf,a3d2de7675556553a5f08e4c88d2c228fib6p,0.0,2007533.0,ntjde,jewelry,phone59,9.770758e+15,ru,79.72.96.0,9ov8hm82p20sxlz

In [42]:
df.loc[df["outcome"] == 1.0]

,bidder_id,payment_account,address,outcome,bid_id,auction,merchandise,device,time,country,ip,url
Unnamed: 0,,,,,,,,,,,,
3793,5354c02817e47f28e60e44a40ca5e48dll4sz,1862ef3b7965993cc975a1161010e810w2bwo,58e5dc4d38d886f6c7abf0c264a51cb7alhj2,1.0,2519801.0,1l3p3,mobile,phone65,9.632357e+15,id,246.142.185.135,vasstdc27m7nks3
3794,5354c02817e47f28e60e44a40ca5e48dll4sz,1862ef3b7965993cc975a1161010e810w2bwo,58e5dc4d38d886f6c7abf0c264a51cb7alhj2,1.0,2543489.0,62d9x,mobile,phone557,9.632436e+15,id,246.142.185.135,vasstdc27m7nks3
3795,5354c02817e47f28e60e44a40ca5e48dll4sz,1862ef3b7965993cc975a1161010e810w2bwo,58e5dc4d38d886f6c7abf0c264a51cb7alhj2,1.0,2556174.0,62d9x,mobile,phone212,9.632481e+15,id,246.142.185.135,vasstdc27m7nks3
3796,5354c02817e47f28e60e44a40ca5e48dll4sz,1862ef3b7965993cc975a1161010e810w2bwo,58e5dc4d38d886f6c7abf0c264a51cb7alhj2,1.0,2562889.0,436hc,mobile,phone20,9.632506e+15,id,246.142.185.135,vasstdc27m7nks3
3797,5354c02817e47f28e60e44a40ca5e48dll4sz,1862ef3b7965993cc975a1161010e810w2bwo,58e5dc4d38d886f6c7abf0c264a51cb7alhj2,1.0,2856456.0,1l3p3,mobile,phone55,9.634185e+15,id,246.142.185.135,vasstdc27m7nks3
...,...,...,...,...,...,...,...,...,...,...,...,...
3070649,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,4729907.0,gja6c,sporting goods,phone148,9.643161e+15,uk,233.151.159.176,yxlccopjmr1t4sz
3070650,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,4731149.0,x36iy,sporting goods,phone232,9.643171e+15,us,234.42.216.39,yxlccopjmr1t4sz
3070651,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,4732373.0,n2eh8,sporting goods,phone168,9.643180e+15,us,161.36.158.177,yxlccopjmr1t4sz
3070652,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,5635516.0,x36iy,sporting goods,phone65,9.697713e+15,cn,171.100.154.82,vasstdc27m7nks3
3070653,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,7242949.0,jqx39,sporting goods,phone65,9.706949e+15,cn,115.6.15.187,vasstdc27m7nks3

In [45]:
# Find number of null values 
df.isnull().sum()

bidder_id             0
payment_account       0
address               0
outcome               0
bid_id               29
auction              29
merchandise          29
device               29
time                 29
country            2730
ip                   29
url                  29
dtype: int64

In [49]:
df[df["bid_id"].isnull()]

,bidder_id,payment_account,address,outcome,bid_id,auction,merchandise,device,time,country,ip,url
Unnamed: 0,,,,,,,,,,,,
17583,5f50c6187a179e2ee7ba2fbcfc845c7a1smgr,7326f0a1592b18cb1e6ed7c8ebbd03a72qf7p,a3d2de7675556553a5f08e4c88d2c228uaoqg,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42424,02bde521e763e4f4e590e8368149e04a96il9,a3d2de7675556553a5f08e4c88d2c2286r1lb,935d2083173e96f099816c1b1f7ee249kk8zo,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129439,dd661e2d6e79a5b3e66c82373d50f3ee86k85,e805bf9d2399ddc37a194e04703a333c7bv82,2c2b8b44b1615ef6d632fb115a85794djmktr,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214915,908ce7060337fd8550760a100921f6f7wsemn,a3d2de7675556553a5f08e4c88d2c2282yldz,39b2bdec29461f8a0ae2a5a5b01d259fik8r7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221776,b64c209b3d1d91a663d134961af89125u0s9a,f7558102989f5665bbbea00358f8434adf9o9,5c9de1da50cc32a29ffd596ae24cd2be24cly,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226432,96b1df591dbbf3a002578574671d9ff1rmzev,a3d2de7675556553a5f08e4c88d2c2288tx3v,1a1d480ca96a50e5fa8af28cf9121d80gx8g2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255107,d2138bce99f535c244dab68652ccfa2enshxk,72a51aa2faf94e7ffdf736fdb389d4efpyojt,458d233d676d8f62406213ab319b8334dbdxh,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305088,c08e5e3325e2f4fea171f24ca018e675we8kj,efd15ad70741e38f212ac919ca569615r3g33,81d6c498369ab4af3fea529406dc7d96flle8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333331,187636e527504df29bf42d4a2b7767e54bgv7,a3d2de7675556553a5f08e4c88d2c2281swzb,a3d2de7675556553a5f08e4c88d2c2281rrln,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409451,74f153bd134afc92866a6bc5cceb2088120y0,a3d2de7675556553a5f08e4c88d2c228fd0s8,796f3dd849480319c21677833dc1a6c87c6p1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654549,4b3e6a8a52c413a32f76a6d7a84a54bb8gb0t,ef57fc6d955628b73e7b49927b3a9a92smhs1,03a2f817014a39b3e162b5bebc266b38ou4ii,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
657208,4d0d345f552877998f41ba3cd1ba299885vu5,a3d2de7675556553a5f08e4c88d2c2287qzaj,5924a488253da832477795257e69d4d2pbdwx,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
788183,59fe751fb6c277016b7ebe3609aa1b15vhg7w,a3d2de7675556553a5f08e4c88d2c228uszco,ea349e9643eac4a7bfd988257e7bea33e8zvd,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790914,d1780c224460a0c20d5c2f5f68714c5264xd0,a3d2de7675556553a5f08e4c88d2c228isxlr,a3d2de7675556553a5f08e4c88d2c2283li9a,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
794927,dc9a7ebdb6fb8dd3267ac26dbe5a62b68e4vw,bde1355fc6c862b13f039caf3f956541h3cbo,a3d2de7675556553a5f08e4c88d2c228kiru5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810369,1e3642857c10e72cedaf7890e3c07bfa8ibzv,a3d2de7675556553a5f08e4c88d2c228hydky,adfe268fb0ff0bfb337a195a3987f1c1axk7b,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883351,4444bfb455b90711234e0c25345abbaddrt0x,1b223b8687ec3408c7cd13c1582e5cf89m6r9,94ffc372dce471cc407d01eb2491950cw4jip,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018748,c62a6956e93ac3b56b1292f2c2d85b1fyekav,a3d2de7675556553a5f08e4c88d2c228vak14,a3d2de7675556553a5f08e4c88d2c2282rsry,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019599,1214fbf35079e7afc0a35645f8be8b218fd5o,1125b4a1f6328a4e97de0fcee423c5c87vg6o,ca0287783f4732fe85bea36c0485b3bb1hzax,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021349,f9378eb3e522beef7e6a4e1f275bbe0eaboro,a3d2de7675556553a5f08e4c88d2c2285ew0e,eef1d3edbcdad054cf65255852f8ad9336zui,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1123023,977436b0a445fa555d537fbf1d4bff2e4z40h,a3d2de7675556553a5f08e4c88d2c228dbc6k,a3d2de7675556553a5f08e4c88d2c228ni64o,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1139921,7a3378ad9999b1fde0a4562a9b036f038cdal,a3d2de7675556553a5f08e4c88d2c228xb0m4,8b364fa601af02d98e6a142050de9a8fp5n4z,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1217466,3de66f8a5453943040d42e1e73f11eebll8h9,a3d2de7675556553a5f08e4c88d2c2287c9l0,f7b3a012d9f0b6931dc0a8dcc9ecc4c5q6r9o,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1465813,c8cf68aa6abce25325dfdad4a98fd890ap57f,a3d2de7675556553a5f08e4c88d2c228yinlc,b98f270a217ec53294c334d2936eb7f7gsi4l,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482542,a4475cf8808f8951dd5163ded3ee8032g9vxd,a3d2de7675556553a5f08e4c88d2c2288r2dg,0b697d222013b544c8fe4ce8540c68149pes0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1648201,db12e9cad5e847cd7a40ec1ee649e475iwzqo,30a9f295085433ca3a1a3cea9b644d24ytevw,aaed475d3674cbb9326ac06ff4fc46f784v20,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1974826,40fafe756c4695b32df7d19d4c710dabvzr79,0db78cbafef79ad159f93d913aafe769b7j2b,a3d2de7675556553a5f08e4c88d2c22877mou,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2139077,583ce05b5add00d9e7e5dcefb3c436f26d7c2,a3d2de7675556553a5f08e4c88d2c2283q3p6,31a7ecb2eedae970ece2ff50761acdeaxwtun,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999380,4fcdd880c4e1a1767c4d26f74bb3466f11osj,a3d2de7675556553a5f08e4c88d2c228ma0xs,3a7e6a32b24aeab0688e91a41f3188e23njk7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
# All of the bid_id null values are by humans - same for columns other than country..... so they can be removed 
# (https://stackoverflow.com/questions/13413590/how-to-drop-rows-of-pandas-dataframe-whose-value-in-a-certain-column-is-nan)
df = df[df["bid_id"].notna()]

In [51]:
df.isnull().sum()

bidder_id             0
payment_account       0
address               0
outcome               0
bid_id                0
auction               0
merchandise           0
device                0
time                  0
country            2701
ip                    0
url                   0
dtype: int64

In [67]:
# Rows with null country values
country_null = df[df["country"].isnull()]

In [68]:
country_null

,bidder_id,payment_account,address,outcome,bid_id,auction,merchandise,device,time,country,ip,url
Unnamed: 0,,,,,,,,,,,,
435,fa64831ab5ade55daee13f852c16b0a84ujt0,3a0add7fb226e9f304c27e80d6d09bfbuarcp,8de27ed2fba662e2e1427856058fae573rszo,0.0,3663612.0,jqx39,mobile,phone106,9.637851e+15,NaN,129.60.14.86,p07idte94085bcb
770,fa64831ab5ade55daee13f852c16b0a84ujt0,3a0add7fb226e9f304c27e80d6d09bfbuarcp,8de27ed2fba662e2e1427856058fae573rszo,0.0,5482432.0,jqx39,mobile,phone65,9.696486e+15,NaN,80.165.83.13,rm77nw8nyin6vou
811,fa64831ab5ade55daee13f852c16b0a84ujt0,3a0add7fb226e9f304c27e80d6d09bfbuarcp,8de27ed2fba662e2e1427856058fae573rszo,0.0,5754111.0,jqx39,mobile,phone1146,9.698575e+15,NaN,22.25.169.40,rm77nw8nyin6vou
2505,d91a4421996dcf429f575e372915cdcedae6g,a3d2de7675556553a5f08e4c88d2c2286gew9,e350bda3ceb6067cad400ae931c3527aetdd8,0.0,38103.0,55y7n,office equipment,phone125,9.759356e+15,NaN,52.166.161.61,3u606u9e94v579x
2535,d91a4421996dcf429f575e372915cdcedae6g,a3d2de7675556553a5f08e4c88d2c2286gew9,e350bda3ceb6067cad400ae931c3527aetdd8,0.0,99655.0,1rc8d,office equipment,phone125,9.759534e+15,NaN,106.18.6.241,pdlypyh8d50omks
...,...,...,...,...,...,...,...,...,...,...,...,...
3064972,717a0a200628f9606d88afebaaeb409bv60y8,fcc90337693238ed69a24820c75fa136yrqj9,1a3e554e23e169897e4988e633fc0244oz819,0.0,3714878.0,jqx39,home goods,phone974,9.638291e+15,NaN,255.102.46.105,fn1p0698sfcsn9d
3066978,717a0a200628f9606d88afebaaeb409bv60y8,fcc90337693238ed69a24820c75fa136yrqj9,1a3e554e23e169897e4988e633fc0244oz819,0.0,6297860.0,jqx39,home goods,phone22,9.701217e+15,NaN,159.144.193.25,e797yw3jx54xp14
3067853,717a0a200628f9606d88afebaaeb409bv60y8,fcc90337693238ed69a24820c75fa136yrqj9,1a3e554e23e169897e4988e633fc0244oz819,0.0,7137772.0,jqx39,home goods,phone82,9.705951e+15,NaN,177.67.238.164,jz5kdap0g1yvek6
3070605,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,4654996.0,obbny,sporting goods,phone46,9.642534e+15,NaN,211.148.232.61,yxlccopjmr1t4sz
3070634,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,4705073.0,62d9x,sporting goods,phone938,9.642962e+15,NaN,32.58.164.139,yxlccopjmr1t4sz

In [69]:
# Some robot bids observed in the country_null dataframe.... let's see what the total number of rows with 
# outcome = 1 and country = null is 
country_null = pd.DataFrame(country_null)

In [72]:
country_null[country_null["outcome"] == 1.0]

,bidder_id,payment_account,address,outcome,bid_id,auction,merchandise,device,time,country,ip,url
Unnamed: 0,,,,,,,,,,,,
17759,9434778d2268f1fa2a8ede48c0cd05c097zey,ee3295c7b31a1e9116ebf0cf2df68ed1ac8ts,627fe7481f01372c02333477471cb237qt2vf,1.0,2509321.0,jqx39,jewelry,phone11,9.632324e+15,NaN,238.33.144.240,uj2r9kdprdhq55z
19078,9434778d2268f1fa2a8ede48c0cd05c097zey,ee3295c7b31a1e9116ebf0cf2df68ed1ac8ts,627fe7481f01372c02333477471cb237qt2vf,1.0,3340700.0,jqx39,jewelry,phone159,9.636584e+15,NaN,5.9.199.181,p74lt2aghe69063
19457,9434778d2268f1fa2a8ede48c0cd05c097zey,ee3295c7b31a1e9116ebf0cf2df68ed1ac8ts,627fe7481f01372c02333477471cb237qt2vf,1.0,3611339.0,jqx39,jewelry,phone16,9.637548e+15,NaN,8.111.92.66,5194xwj7t2bkj68
19481,9434778d2268f1fa2a8ede48c0cd05c097zey,ee3295c7b31a1e9116ebf0cf2df68ed1ac8ts,627fe7481f01372c02333477471cb237qt2vf,1.0,3650531.0,jqx39,jewelry,phone16,9.637764e+15,NaN,8.111.92.66,vvz8gy36ao069wx
20170,9434778d2268f1fa2a8ede48c0cd05c097zey,ee3295c7b31a1e9116ebf0cf2df68ed1ac8ts,627fe7481f01372c02333477471cb237qt2vf,1.0,3987879.0,jqx39,jewelry,phone125,9.640127e+15,NaN,189.84.140.155,it9vpyfxtqbpn8k
...,...,...,...,...,...,...,...,...,...,...,...,...
2765794,5f529b5ee68b60482c5d0c56ee91f3c2cjrmx,323a6be18d0d4adb0353040403acca122wu7i,779379b162ae02d269f42ae8c639bafb9pdx1,1.0,1448093.0,aeqok,office equipment,phone887,9.767802e+15,NaN,121.19.166.33,vasstdc27m7nks3
2766263,5f529b5ee68b60482c5d0c56ee91f3c2cjrmx,323a6be18d0d4adb0353040403acca122wu7i,779379b162ae02d269f42ae8c639bafb9pdx1,1.0,1913991.0,7msk4,office equipment,phone233,9.769890e+15,NaN,218.56.160.127,0eo1lc3fdxkvq5t
3034576,458c8c4e10e5c1b29e3fbe5ee56d46e8y3fb3,97ee873207ff7c57e70c50637c93c11eqsyjy,480aca092e44d3e23a015e51d8e7daa4hhcss,1.0,1002524.0,jefix,sporting goods,phone21,9.764561e+15,NaN,212.71.248.203,grs853ocad7rm8o
3070605,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,4654996.0,obbny,sporting goods,phone46,9.642534e+15,NaN,211.148.232.61,yxlccopjmr1t4sz
3070634,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0,4705073.0,62d9x,sporting goods,phone938,9.642962e+15,NaN,32.58.164.139,yxlccopjmr1t4sz

In [73]:
# Very small minority of robotic bids have null for country.... we will remove those 
df = df[df["country"].notna()]

In [74]:
df.isnull().sum()

bidder_id          0
payment_account    0
address            0
outcome            0
bid_id             0
auction            0
merchandise        0
device             0
time               0
country            0
ip                 0
url                0
dtype: int64

In [76]:
df.to_csv("cleaned_dataset.csv", index = False)